### PR TITLE
Update Docker and WebService Setup

### PR DESCRIPTION
**Pull request by PSchmiedmayer**
# Update Docker and WebService Setup

## :recycle: Current situation
The current docker compose setup doesn't properly start and expose the web service and the Apodini web service is not using the latest Apodini version.

## :bulb: Solution
Update the docker compose and web service files.
- The web service is reachable at port 8080.
- The web frontend is reachable at port 80, enabling to access it by entering http://localhost in the address bar of your browser.
- Removes the not needed reverse proxy from the docker compose setup when building locally.
- Remove unused volumes.
- Updated the README to describe the setup (e.g. including the MapBox Key) in more detail.
- Added a license and contributors file.

## ⚙️ Open Issues
There are currently three issues that need further investigation:
- [ ] The frontend web application doesn't seem to properly load data from the web service in the setup found in the `docker-compose.yml` setup. It also seems like the frontend is fixed on a specific date.
- [ ] Observability: Some request in the `test_observability.sh` test script seem to fail as highlighted when adding the failure flags.
- [ ] Observability: The Graphana Dashboard doesn't seem to work as described in the README. The small "ApodiniObserve example" dashboard that should be accessible unter "Dashboards > Manage" can not be found.

### CODE REVIEW

**Comment by philippzagar** [comment]
@PSchmiedmayer As mentioned via Rocketchat, I'll take a closer look into the issues on Friday :)
Sadly, I wasn't really involved in the frontend part, but I'm sure we'll find a solution

**Comment by moritzsternemann** [comment]
*I hope my new commits to the branch will show up in the PR eventually, seems like there is a service degradation at GitHub currently ([githubstatus.com](https://www.githubstatus.com)).*

I fixed a few issues, mainly misspelled default dates, in the frontend. Additionally I aligned used and exposed ports in the production and development docker-compose files. The Apodini web service now runs on port 8080 and Grafana is exposed on port 4000 so that it doesn't interfere with the React dev-server on port 3000.

Unfortunately, there are still a few more issues, which I'd love to get your input on (most affect the first open issue from the PR description):
- The npm `start` script starts a development server with a lot of features that are not intended for production deployments and slow down the JavaScript app. The [create-react-app docs](https://create-react-app.dev/docs/deployment) suggest to run a production build of the app and serve it using a static file server (is there a static file handler in Apodini? 🤔).
- If we decide to serve the frontend using any other server than the Apodini web service, CORS restricts the frontend from requesting the API on another *origin* than its own (different domain, scheme, or port). To resolve this, we have two options. We can adjust the CORS headers of the frontend server to allow contacting the API on port 8080. Or we can add the reverse proxy again, so that the frontend and the web service are reachable at the same origin.
- There are errors in the JavaScript console that indicate Redux has a problem handling `Date` objects. We should probably change these to integer timestamps.
- There are a lot of warnings in the in the React app but I don't have any experience with the framework. I can probably find out how to solve them but this will take additional time, which is scarce at the moment 😇.

**Comment by philippzagar** [comment]
@moritzsternemann thanks for taking a look into it, sadly i have a huge submission on Monday, therefore I won't be able to take a closer look into it.
I also pushed some of my fixes, you can take a look into them.
To be honest, I would simply restore the reverse proxy in order to fix some of the issues listed above. The development of the entire application was done in basically 5-6 days (mostly by beginners in the respective technologies), therefore neither the code quality nor the general architecture is really good or something 😅 Also, i wouldn't worry too much about some React warnings etc., i think that isn't the focus of @PSchmiedmayer dissertation where he uses this project as an example

**Comment by philippzagar** [comment]
@moritzsternemann I also pushed the grafana dashboard files, they really were exempt via a gitignore file in the respective directory and therefore only existed "locally" on my machine :)
-> Therefore I hope that at least the dashboard part works again

**Comment by PSchmiedmayer** [comment]
@moritzsternemann Thanks for taking a look at the issues! I completely agree that reading the reverse proxy makes a lot of sense, I thought it wasn't needed but must have completely overlooked the CORS header!

**Comment by moritzsternemann** [comment]
I added the reverse proxy back in, documented the exposed services in the readme, and the frontend is now built and served in production mode.

**Comment by PSchmiedmayer** [comment]
@moritzsternemann Thanks a lot! 💪

**Comment by PSchmiedmayer** [comment]
@moritzsternemann I tested out the current state of the branch using `docker compose up --build` and the Apodini Web Service seems to crash with the following log message:
```
info org.apodini.application : Starting without HTTP/2 and TLS
notice org.apodini.application : [Router] added GET route at '/metrics'
info org.apodini.application : Metrics data of PrometheusMetricsFactory(client: Prometheus.PrometheusClient, configuration: Prometheus.PrometheusMetricsFactory.Configuration(labelSanitizer: Prometheus.PrometheusLabelSanitizer(), timerImplementation: Prometheus.PrometheusMetricsFactory.TimerImplementation(_wrapped: Prometheus.PrometheusMetricsFactory.TimerImplementation._Wrapped.summary(defaultQuantiles: [0.01, 0.05, 0.5, 0.9, 0.95, 0.99, 0.999])), defaultRecorderBuckets: Prometheus.Buckets(buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 1.7976931348623157e+308]))) served on /metrics
```
Without any indication of why the web service crashed. I have tested updating the Apodini Dependency to `.branch("lukaskollmer/improve-param-decoding")` which seems to resolve the startup issue but the communication with the web frontend doesn't seem to work with that. I am not sure if this is the same with the current committed version as it doesn't startup.

**Comment by PSchmiedmayer** [comment]
I have tested the latest commit of this PR and it seems there bis still a problem with the frontend and the observability features.
I have made a clean clone of the repo, checke out this branch and also cleaned all docker-related data (using the _Clean / Purge data_) function in the Docker Dashboard troubleshoot setting. And then started the test script using `sh test_observability.sh`
After the 6. request I get the following error message:
```
curl: (22) The requested URL returned error: 500
ApodiniError(type: Apodini.ErrorType.badInput, reason: Optional("The Authentication is no correct basic format"), description: nil, information: Apodini.InformationSet(storage: [:], capturedInstantiatables: [:]), options: Apodini.PropertyOptionSet<Apodini.ErrorOptionNameSpace>(options: [:]))curl: (22) The requested URL returned error: 500
ApodiniError(type: Apodini.ErrorType.badInput, reason: Optional("The Authentication is no correct basic format"), description: nil, information: Apodini.InformationSet(storage: [:], capturedInstantiatables: [:]), options: Apodini.PropertyOptionSet<Apodini.ErrorOptionNameSpace>(options: [:]))
```
All subsequent calls seem to work as expected.

The WebUI seems to display no data and crashes on the export screen: 

https://user-images.githubusercontent.com/28656495/152046996-bc802b16-adaa-42d1-9b26-b3b257b37601.mp4

The Elastic Dashboard looks good:
Screen Shot 2022-02-01 at 9 29 20 PM

The Prometheus data as well as the Grafana Dashboard don't seem to get any data:
Screen Shot 2022-02-01 at 9 30 34 PM
Screen Shot 2022-02-01 at 9 30 57 PM

**Comment by philippzagar** [comment]
Observability functionality should work again, however the frontend part is still a work in progress.

**Comment by philippzagar** [comment]
The failures of the request is actually intended as Apodini collects observability metrics of the failure rate and displays it in Grafana :)

**Comment by philippzagar** [comment]
The frontend should now display some dummy data again, demonstrating the ability of the React frontend to fetch some data of the Apodini backend

**Comment by moritzsternemann** [comment]
@PSchmiedmayer I fixed some more issues in the frontend. One was causing an error on the Export page and should be solved now.

**Comment by philippzagar** [comment]
Nice, thanks @moritzsternemann !

**Review by moritzsternemann — APPROVED** [review]
If all issues are resolved for you @PSchmiedmayer, I think we can merge this 🚀

**Review by philippzagar — APPROVED** [review]

**Comment by PSchmiedmayer** [comment]
Thanks again @philippzagar and @moritzsternemann for the amazing support! I plan to tag a new Apodini release with the changes in the next days and will then merge the PR pointing to a proper release 👍

**Pull request merged**
